version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    ports:
      - "3000:3000"
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
